### ISSUE TITLE
Mobile Version?

### ISSUE THREAD

**Issue by crchong1** [keepid/team-keep#8]
Might be good to make a figma for how these things will resize

**Comment by crchong1** [comment]
maybe you don't need to modify the figma, but maybe just think about how this will resize? I actually think this is quite important as many people will look at the donor page on mobile

**Comment by danielsjoo** [comment]
**Major issues:**

home page: fix awkward padding and margins between components in mobile view.
<img src="https://user-images.githubusercontent.com/68679808/124682700-4cc39b80-de80-11eb-8eb4-c80d5632a9b1.png" width="200"> <img src="https://user-images.githubusercontent.com/68679808/124683042-0b7fbb80-de81-11eb-9998-abe153aa47ff.png" width="200"> <img src="https://user-images.githubusercontent.com/68679808/124683069-18041400-de81-11eb-986b-b5956c8f8775.png" width="200">

Issues:
Fix text going over the page in mobile page
<img src="https://user-images.githubusercontent.com/68679808/124682662-33baea80-de80-11eb-9d0b-c6c4f302dabd.png" width="200">

About us:
place icons above text instead of over
<img src="https://user-images.githubusercontent.com/68679808/124682640-23a30b00-de80-11eb-8007-e248a3268a5a.png" width="200">

**Minor issues:**

Issues, About Us:
Images simply get cropped horizontally as the screen narrows. See if resizing the images work better.
<img src="https://user-images.githubusercontent.com/68679808/124682757-7381d200-de80-11eb-95dd-dffc19156295.png" width="200">

Home Page, Issues:
At some places, components are not vertically centered when they are on the full page
<img src="https://user-images.githubusercontent.com/68679808/124682837-9ca26280-de80-11eb-9b2d-d9f1430e9db6.png" width="200"> <img src="https://user-images.githubusercontent.com/68679808/124682965-eb4ffc80-de80-11eb-8c71-1fa4dcac7978.png" width="200">
